name: Update streams data

on:
  workflow_dispatch: # кнопка
    inputs:
      limit:
        description: "Сколько стримов обрабатывать"
        required: false
        default: "5"
  schedule:
    - cron: "0 13 * * 1"

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -U "yt-dlp[default]" pillow imagehash

      - name: Run worker
        id: worker
        run: |
          python worker/main.py --limit ${{ github.event.inputs.limit || 5 }}
        continue-on-error: false

      - name: Get date
        id: date
        uses: Kaven-Universe/github-action-current-date-time@v1
        with:
          format: "YYYY-MM-DD"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        id: cpr
        with:
          branch: update-streams-${{ steps.date.outputs.time }}
          commit-message: "${{steps.date.outputs.time}} | Update streams data"
          title: "${{steps.date.outputs.time}} | Автообновление стримов"
          base: master
          token: ${{ secrets.GH_PAT_TOKEN }}
          delete-branch: true

      - name: Notify Telegram
        if: steps.cpr.outputs.pull-request-url != ''
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage" \
          -d chat_id="${{ secrets.TG_CHAT_ID }}" \
          -d text="🆕 (${{steps.date.outputs.time}}) Новый PR создан: ${{ steps.cpr.outputs.pull-request-url }}"
