name: Update streams data

on:
  workflow_dispatch: # кнопка
  schedule:
    - cron: "0 13 * * 1"

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -U "yt-dlp[default]"

      - name: Run worker
        id: worker
        run: |
          python worker/worker.py
        continue-on-error: false

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: update-streams
          commit-message: "Update streams data"
          title: "Автообновление стримов"
          body: "Добавлены новые стримы автоматически"
          base: master
